openapi: 3.0.0
x-stoplight:
  id: swtfnrmy4o30q
info:
  title: TodoSample
  version: '1.0'
  description: |-
    TODOリストを管理するアプリのためのサンプル用OpenAPI
    認証機能はCongitoを利用するToken認証方式
  contact:
    name: Hayato Takahashi
    url: 'https://github.com/HayatoTakahashi129'
    email: hayato.012995@gmail.com
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
servers:
  - url: 'http://localhost:3000'
paths:
  /todos:
    get:
      summary: TODOリスト取得
      responses:
        '200':
          description: TODOリスト取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    x-stoplight:
                      id: laopnxfqpoied
                    type: array
                    items:
                      x-stoplight:
                        id: fls1knnd5t7rr
                      allOf:
                        - $ref: ./models/ID.yaml
                          x-stoplight:
                            id: 48xge8sle0slz
                        - $ref: '#/components/schemas/Todo'
                          x-stoplight:
                            id: rkg43xolzcc99
                required:
                  - data
              examples:
                登録されているTODOがない場合:
                  value:
                    data: []
                TODOリストが登録済みの場合（２件）:
                  value:
                    data:
                      - id: '165923165886004186925843853365'
                        title: ごみを出す
                        dueDate: '2022-07-07T08:00:00+09:00'
                        description: 次の火曜日に朝８時までにごみを出す
                      - id: '165923165886004186925843853368'
                        title: ごみを出す2
                        dueDate: '2022-07-09T08:00:00+09:00'
                        description: 次の木曜日に朝８時までにごみを出す
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '429':
          $ref: '#/components/responses/TooManyRequestError'
        '500':
          $ref: '#/components/responses/SystemError'
        '503':
          $ref: '#/components/responses/SystemBlockage'
        '504':
          $ref: '#/components/responses/TimeoutError'
      operationId: get-todos
      description: |
        TODOリストの一覧を配列形式で取得する。  
      security:
        - ID-Token: []
      requestBody:
        content: {}
      tags:
        - Todo
    post:
      summary: TODO追加
      operationId: post-todos
      responses:
        '200':
          description: TODOの新規登録に成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                    x-stoplight:
                      id: 2qns5fryxx4b9
                  - type: object
                    properties:
                      data:
                        x-stoplight:
                          id: r6eyvt4papimy
                        allOf:
                          - $ref: ./models/ID.yaml
                            x-stoplight:
                              id: gruru0tw6ypna
                          - $ref: '#/components/schemas/Todo'
                            x-stoplight:
                              id: p9hvhjzlq87ls
                    required:
                      - data
              examples:
                TODO登録成功:
                  value:
                    message:
                      type: success
                      display: TODOの作成に成功しました。
                    data:
                      id: '165923165886004186925843853365'
                      title: ごみを出す
                      dueDate: '2022-07-07T03:00:00+09:00'
                      description: 次の火曜日に朝８時までにごみを出す
        '400':
          description: 業務エラー発生
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                  - $ref: ./models/Error.yaml
                    x-stoplight:
                      id: xpfus3li8001o
              examples:
                バリデーションエラー:
                  value:
                    message:
                      type: failure
                      display: |-
                        入力内容に誤りがあります。
                        再度ご確認の上実施をお願いいたします。
                    error:
                      type: validation
                      detail: '${name}欄の入力は必須になります。'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '429':
          $ref: '#/components/responses/TooManyRequestError'
        '500':
          $ref: '#/components/responses/SystemError'
        '503':
          $ref: '#/components/responses/SystemBlockage'
        '504':
          $ref: '#/components/responses/TimeoutError'
      description: TODOを新たに登録する
      security:
        - ID-Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/Todo'
                  x-stoplight:
                    id: z7oyxqmt6xk8w
      tags:
        - Todo
  '/todos/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: TODOの識別用ID
    get:
      summary: TODO詳細情報取得
      responses:
        '200':
          description: TODO詳細情報取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    x-stoplight:
                      id: b83jq8bluoen7
                    allOf:
                      - $ref: ./models/ID.yaml
                        x-stoplight:
                          id: iiemm9mk7apd7
                      - $ref: '#/components/schemas/Todo'
                        x-stoplight:
                          id: 3eb8pc2v6gkcv
                required:
                  - data
              examples:
                情報取得成功:
                  value:
                    data:
                      id: '165923165886004186925843853365'
                      title: ごみを出す
                      dueDate: '2022-07-07T03:00:00+09:00'
                      description: 次の火曜日に朝８時までにごみを出す
        '400':
          description: 業務エラー発生
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                  - $ref: ./models/Error.yaml
                    x-stoplight:
                      id: uh4me35n9bgx1
              examples:
                存在しないIDを指定した場合:
                  $ref: '#/components/examples/NotExistIdError'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '429':
          $ref: '#/components/responses/TooManyRequestError'
        '500':
          $ref: '#/components/responses/SystemError'
        '503':
          $ref: '#/components/responses/SystemBlockage'
        '504':
          $ref: '#/components/responses/TimeoutError'
      operationId: get-todos-id
      description: TODOの詳細情報を取得
      security:
        - ID-Token: []
      tags:
        - Todo
    put:
      summary: TODO詳細情報更新
      operationId: put-todos-id
      responses:
        '200':
          description: TODOの詳細情報更新成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                    x-stoplight:
                      id: n3axv5jul4rb5
                  - type: object
                    properties:
                      data:
                        x-stoplight:
                          id: n78hmnge76xos
                        allOf:
                          - $ref: ./models/ID.yaml
                            x-stoplight:
                              id: irkwsab3s9pwo
                          - $ref: '#/components/schemas/Todo'
                            x-stoplight:
                              id: 426czg5iza98e
                    required:
                      - data
              examples:
                TODOの更新に成功:
                  value:
                    message:
                      type: success
                      display: TODOの更新に成功しました。
                    data:
                      id: '165923165886004186925843853365'
                      title: ごみを出す
                      dueDate: '2022-07-07T03:00:00+09:00'
                      description: 次の木曜日に朝８時までにごみを出す
        '400':
          description: 業務エラー発生
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                  - $ref: ./models/Error.yaml
                    x-stoplight:
                      id: 06tbilqp2fkbj
              examples:
                存在しないIDを指定した場合:
                  $ref: '#/components/examples/NotExistIdError'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '429':
          $ref: '#/components/responses/TooManyRequestError'
        '500':
          $ref: '#/components/responses/SystemError'
        '503':
          $ref: '#/components/responses/SystemBlockage'
        '504':
          $ref: '#/components/responses/TimeoutError'
      description: TODOの詳細情報を更新する
      security:
        - ID-Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/Todo'
                  x-stoplight:
                    id: c3j6pkiyq8rhj
        description: ''
      tags:
        - Todo
    delete:
      summary: TODO削除
      operationId: delete-todos-id
      responses:
        '200':
          description: TODOの削除に成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                    x-stoplight:
                      id: e5uvd896qvikw
                  - type: object
                    properties:
                      data:
                        x-stoplight:
                          id: jeh7oajm6oted
                        allOf:
                          - $ref: '#/components/schemas/Todo'
                            x-stoplight:
                              id: eqal3ti8dli45
                          - $ref: ./models/ID.yaml
                            x-stoplight:
                              id: 433wlieyesin1
                    required:
                      - data
              examples:
                TODO削除成功:
                  value:
                    message:
                      type: success
                      display: TODOの削除に成功しました。
                    data:
                      id: '165923165886004186925843853365'
                      title: ごみを出す
                      dueDate: '2022-07-07T03:00:00+09:00'
                      description: 次の火曜日に朝８時までにごみを出す
        '400':
          description: 業務エラー発生
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Message.yaml
                  - $ref: ./models/Error.yaml
                    x-stoplight:
                      id: wubg0vyg4y1ad
              examples:
                存在しないIDを指定した場合:
                  $ref: '#/components/examples/NotExistIdError'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '429':
          $ref: '#/components/responses/TooManyRequestError'
        '500':
          $ref: '#/components/responses/SystemError'
        '503':
          $ref: '#/components/responses/SystemBlockage'
        '504':
          $ref: '#/components/responses/TimeoutError'
      description: TODOを削除する。
      security:
        - ID-Token: []
      tags:
        - Todo
components:
  schemas:
    Todo:
      title: Todo
      x-stoplight:
        id: j8z2lroq15ue4
      type: object
      description: TODO情報を管理するモデル
      properties:
        title:
          type: string
          x-stoplight:
            id: je500wvzehsfs
          description: タイトル
          example: ごみを出す
          minLength: 1
          maxLength: 128
        dueDate:
          type: string
          x-stoplight:
            id: 1lij2dp6rn7ib
          format: date-time
          description: 達成期限
          example: '2022-07-07T03:00:00+09:00'
          minLength: 25
          maxLength: 25
        description:
          type: string
          x-stoplight:
            id: 23py9cgxkgtq9
          description: 詳細情報
          example: 次の火曜日に朝８時までにごみを出す
          minLength: 0
          maxLength: 1024
      required:
        - title
        - dueDate
  securitySchemes:
    ID-Token:
      name: Authorization
      type: apiKey
      in: header
  responses:
    NotAuthorized:
      description: 未ログイン状態・トークンの有効期限切れ状態でのAPIリクエストが実施されたときに返却されるレスポンス
      content:
        application/json:
          schema:
            $ref: ./models/Response/NotAuthorizedResponse.yaml
          examples:
            未認証エラー:
              value:
                error:
                  type: system
                  detail: 未認証状態によるAPI打鍵エラー
    SystemBlockage:
      description: システム閉塞時のエラーレスポンス
      content:
        application/json:
          schema:
            $ref: ./models/Response/SystemBlockageResponse.yaml
          examples:
            システム閉塞メッセージ:
              value:
                message:
                  type: modal
                  display: |-
                    以下の時間帯で現在システムの使用ができません。
                      2023年3月1日 12:00 ~ 2023年3月1日 15:00
                    お手数ですが、上記時間外で再度ログインを実施いただくようお願いいたします。
                error:
                  type: system
                  detail: システム閉塞の実施期間中によるエラー
    SystemError:
      description: バックエンド側で想定外のシステムエラーが発生した時に表示されるエラーレスポンス
      content:
        application/json:
          schema:
            $ref: ./models/Response/SystemErrorResponse.yaml
          examples:
            システムエラー:
              value:
                message:
                  type: modal
                  display: |-
                    想定外のエラーが発生しました。
                    大変お手数ですが、暫くしてから再度お試しください。
                    暫くしても解決しない場合はお手数ですが、「お問い合わせ」画面よりお問い合わせください。
                error:
                  type: system
                  detail: 想定外のバックエンドエラー発生
    TimeoutError:
      description: サーバー側の処理が遅く、タイムアウトエラーが発生した時のエラーレスポンス
      content:
        application/json:
          schema:
            $ref: ./models/Response/TimeoutErrorResponse.yaml
          examples:
            タイムアウトエラー:
              value:
                message:
                  type: modal
                  display: |-
                    処理に時間がかかっており失敗しました。
                    お手数おかけしますが、暫くしてから再度お試しください。
                error:
                  type: system
                  detail: サーバーの処理に時間がかかっていることによるタイムアウトエラー
    TooManyRequestError:
      description: サービスへのアクセスが込み合っているときのエラーレスポンス
      content:
        application/json:
          schema:
            $ref: ./models/Response/TooManyRequestResponse.yaml
          examples:
            リクエスト過多:
              value:
                message:
                  type: modal
                  display: |-
                    現在大変込み合っております。
                    お手数おかけしますが、暫くしてから再度お試しください。
                error:
                  type: system
                  detail: リクエスト過多によるエラー
  examples:
    ResourceMismatchError:
      value:
        message:
          type: modal
          display: ''
        error:
          type: buisiness
          detail: 存在しないIDへアクセスした場合
          action: return
    NotExistIdError:
      value:
        message:
          type: modal
          display: |-
            存在しないリソースへのアクセスを検知しました。
            お手数ですが、前の画面に戻り再度お選びください。
        error:
          type: buisiness
          detail: 存在しないIDへアクセスした場合
          action: return
security:
  - ID-Token: []
